version: '3.7'

services:
  postgres:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/bitnami/redis

volumes:
  polls_redis_data:
  polls_pg_data:

  